import base64
import datetime
import time
import json
import smtplib
import sys
from email import encoders
from email.message import EmailMessage
from email.mime.application import MIMEApplication
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

from config import GMAIL_SENDER, GMAIL_APP_PASSWORD, ARTIFACTS_DIR
from report_models import ClientReportData
from pdf_builders import SummaryReportBuilder
from pdf_builders import get_report_email_body_date
from supabase_storage import fetch_json


def log(msg):
    if isinstance(msg, (dict, list)):
        msg = json.dumps(msg, indent=2, default=str)
    print(f"[{datetime.datetime.now(datetime.timezone.utc).isoformat()}] {msg}", file=sys.stderr, flush=True)


def sanitize_filename(value: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in value).strip("_") or "report"


def format_date_with_suffix(date_obj):
    day = date_obj.day
    if 11 <= day <= 13:
        suffix = "th"
    else:
        suffix = {1: "st", 2: "nd", 3: "rd"}.get(day % 10, "th")
    return f"{day}{suffix} {date_obj.strftime('%B %Y')}"

def build_email_html(client_name: str, today_format: str):
    return f"""
    <html>
      <body style="font-family: Arial, sans-serif; color: #222;">
        <p>Dear {client_name},</p>
        <p>Please find attached the Statements as on {today_format}. Below is a brief explanation of the key parameters included in the report:<br><br>
            1. Absolute Return: Reflects the absolute return on current holdings.<br>
            2. XIRR (Current Holdings): Indicates the annualized return generated by the current portfolio.<br>
            3. XIRR (Since Inception): Shows the annualized return generated since inception.<br>
            4. Allocation represents the internal distribution of assets across the entire portfolio.<br>
            5. For comprehensive details on current holdings and historical booked profits, please visit www.definitif.app/dashboard.<br>
        </p>
        <p>
        Note:<br>
        - Valuations might get delayed by 1 business day in some occations.<br>
        - Data is updated on every Tuesday and at the end of every month.
        </p>
        <p>Regards,</p>
        <table role="presentation" cellpadding="0" cellspacing="0" border="0"
               style="font-family: Arial, Helvetica, sans-serif; font-size: 13px; color: #222; line-height: 1.4; width:auto;">
          <tr>
            <td valign="middle" style="padding-right:10px; border-right:1px solid #e5e5e5; text-align:left; white-space:nowrap;">
              <div style="font-weight:700; font-size:16px; color:#111; margin-bottom:2px;">
                Prashanta Das
              </div>
              <div style="font-size:11px; color:#777; margin-bottom:6px;">
                Investment Manager
              </div>
              <img src="cid:definitiflogo" alt="définitif logo" width="100"
                   style="display:block; border:0; margin-left:0px; outline:0; text-decoration:none;">
            </td>
            <td valign="middle" style="padding-left:10px; text-align:left; white-space:nowrap;">
              <img src="cid:definitifbrand" alt="définitif investments logo" width="80"
                   style="display:block; border:0; outline:0; text-decoration:none;">
              <div style="font-size:8px; color:#777; margin-top:0px; margin-left:4px;">
                ... by définitif investments
              </div>
              <div style="font-size:9px; color:#777; margin-top:4px; margin-left:2px;">
                <a href="https://www.definitif.app">www.definitif.app</a> |
                <a href="mailto:definitif.investments@gmail.com">definitif.investments@gmail.com</a>
              </div>
            </td>
          </tr>
        </table>
      </body>
    </html>
    """


def send_email_with_attachments(
    recipient_email,
    subject: str,
    html_body: str,
    attachment_paths: list[str],
):
    if isinstance(recipient_email, list):
        recipients = [str(x).strip() for x in recipient_email if str(x).strip()]
    else:
        recipients = [str(recipient_email).strip()] if str(recipient_email).strip() else []

    if not recipients:
        raise ValueError("At least one recipient email is required")

    valid_attachments = []
    for file_path in attachment_paths:
        if not file_path:
            continue
        path = Path(file_path)
        if path.exists() and path.is_file():
            valid_attachments.append(path)

    msg = MIMEMultipart("related")
    msg["Subject"] = subject
    msg["From"] = GMAIL_SENDER
    msg["To"] = ", ".join(recipients)

    alt_part = MIMEMultipart("alternative")
    alt_part.attach(MIMEText(html_body, "html"))
    msg.attach(alt_part)

    logo_path = Path("static/email/sign_brand_logo.png")
    brand_path = Path("static/email/sign_echo_logo.png")

    for cid, path in [("definitiflogo", logo_path), ("definitifbrand", brand_path)]:
        if path.exists():
            with open(path, "rb") as f:
                img = MIMEImage(f.read(), _subtype="png")
                img.add_header("Content-ID", f"<{cid}>")
                img.add_header("Content-Disposition", "inline", filename=path.name)
                msg.attach(img)

    for path in valid_attachments:
        with open(path, "rb") as f:
            payload = MIMEApplication(f.read(), _subtype="pdf")
            payload.add_header("Content-Disposition", "attachment", filename=path.name)
            msg.attach(payload)

    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(GMAIL_SENDER, GMAIL_APP_PASSWORD)
        server.send_message(msg)


def fetch_report_json(client_login: str) -> dict:
    portfolio_file = f"{client_login}.json"
    data = fetch_json(portfolio_file)

    if not isinstance(data, dict):
        raise ValueError(f"Invalid report JSON for {client_login}")

    if "data" not in data:
        raise ValueError(f"Missing 'data' key in report JSON for {client_login}")

    return data


def generate_client_reports_from_json(
    report_json: dict,
    client_login: str,
    client_name: str,
    output_dir: str,
):
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    safe_name = sanitize_filename(client_name)
    portfolio_stmt_pdf = str(out_dir / f"Portfolio Statement - {safe_name}.pdf")

    report = ClientReportData.from_dict(report_json["data"])

    builder = SummaryReportBuilder(portfolio_stmt_pdf)
    builder.build(report)

    valuation_date = None
    kpi = getattr(report, "kpi", None)
    if kpi is not None:
        valuation_date = getattr(kpi, "val_date", None)

    return {
        "portfolio_stmt_pdf": portfolio_stmt_pdf,
        "valuation_date": valuation_date,
    }


def run_client_report_job(
    client_login: str,
    client_name: str,
    recipients: list[str],
    ):
    log(f"START client={client_login}")
    log(f"Generating reports for {client_name}")

    reports = None
    try:
        t0 = time.time()
        report_json = fetch_report_json(client_login)
        log("Fetched report JSON")
        log(f"fetch_report_json took {time.time() - t0:.2f}s")

        t1 = time.time()
        reports = generate_client_reports_from_json(
            report_json=report_json,
            client_login=client_login,
            client_name=client_name,
            output_dir=str(Path(ARTIFACTS_DIR) / "email_reports" / client_login),
        )
        log(reports)

        log(
            f"Reports generated. "
            f"portfolioStmt={reports['portfolio_stmt_pdf']} "
            f"pdf build took {time.time() - t1:.2f}s"
        )

        attachments = [
            p for p in [reports["portfolio_stmt_pdf"]] if p
        ]
        log(f"Attachments found: {len(attachments)}")

        email_sent = False

        if recipients:
            log(f"Recipients: {recipients}")
        else:
            log("No recipients")

        report_email_body_date = reports.get("valuation_date") if isinstance(reports, dict) else None
        if not report_email_body_date:
            report_email_body_date = format_date_with_suffix(dt.date.today())

        email_sent = False    
        if recipients and attachments:
            t2 = time.time()
            log("Starting email send")
            send_email_with_attachments(
                recipient_email=recipients,
                subject=f"Portfolio Statements as on {report_email_body_date} - {client_name}",
                html_body=build_email_html(client_name, report_email_body_date),
                attachment_paths=attachments,
            )
            log("Email send completed")
            log(f"email send took {time.time() - t2:.2f}s")
            email_sent = True
        else:
            log("Skipping email send")

        log(f"END client={client_login}")

        return {
            "login": client_login,
            "clientName": client_name,
            "recipients": recipients,
            "portfolioStmtPdf": bool(reports["portfolio_stmt_pdf"]),
            "emailSent": email_sent,
            "attachments": attachments,
        }

    except Exception as e:
        log(f"FAILED client={client_login}: {repr(e)}")
        raise